### ISSUE TITLE
Sticky Navbar

### ISSUE THREAD

**Issue by schramls** [Jonas-Pamminger/WMC_ARWebsite#15]
Navigation bar / page header scrolls out of view - it should stick to the top of the page.

**Comment by FabianBaitura** [comment]
I made it stick to the top, I need your opinion. Also, is it okay that it can overlap over other Text?
Or should I implement, that it fades out whenever text ist located under it? I just wouldn't see the point of it fading out, since then it would be faded out all the time since theres constantly text. Thank you for your response in advance.
Have a good evening

**Comment by FabianBaitura** [comment]
I found that the sticky Navbar isn't quite working yet. I'll make a new branch and work on it. Were having a little bit of trouble getting all on the same version of our website. I'll look into it ASAP

**Comment by FabianBaitura** [comment]
navbar should work now, still need your opinion on its looks.

**Comment by Jonas-Pamminger** [comment]
@schramls
